FROM python:3.12-alpine3.18


RUN apk add --no-cache gcc musl-dev postgresql-dev libpq curl


RUN adduser -D -h /appuser appuser
WORKDIR /appuser

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY entrypoint.sh /appuser/entrypoint.sh

RUN sed -i 's/\r$//' /appuser/entrypoint.sh \
 && chmod +x /appuser/entrypoint.sh \
 && mkdir -p /appuser/kv \
 && chown -R appuser:appuser /appuser

ENV PYTHONUNBUFFERED=1
USER appuser

ENTRYPOINT ["/appuser/entrypoint.sh"]
