{
 "title": "Kubernetes / Resources / Azure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API AND ECTD RAM USAGE ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "API SERVER",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "apiserver_memory_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "ECTD",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "etcd_memory_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "API AND ECTD CPU USAGE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "API SERVER CPU",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "apiserver_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "ECTD CPU USAGE",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "etcd_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "Node Ready Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{condition}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "condition",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "kube_node_status_condition",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "PT1H"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "Availabile CPU cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "CPU amount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "customNamespace": "Microsoft.ContainerService/managedClusters",
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "kube_node_status_allocatable_cpu_cores",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "Availabile memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "kube_node_status_allocatable_memory_bytes",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "PODS NUMBER IN CLUSTER",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "kube_pod_status_ready",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "PODS IN CLUSTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "namespace",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "kube_pod_status_ready",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{node}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "node",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "node_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "NETWORK IN by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Network IN in {{node}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "node",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "node_network_in_bytes",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "NETWOR OUT by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Network OUT {{node}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "node",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "node_network_out_bytes",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "DISK USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{node}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "node",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "node_disk_usage_bytes",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inzynierkaaks",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  }
 ]
}