{
 "title": "FunctionApp",
 "tags": [
  "azure",
  "collect_data"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU ENDPOINT USAGE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{cloud/roleinstance}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-worker",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{cloud/roleinstance}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [
         "0--e02a317e-bf43-4150-a135-7823dfe6c4d1",
         "0--c156b4a0-eee3-485b-84a3-1f1e2fda7572",
         "0--fdf3b522-d41a-4ff8-92ad-97b814e56883",
         "0--2894dd94-353b-4047-8329-f811dc25e17d"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-submit",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "RAM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{Instance}} in {{resourceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Microsoft.Web/sites",
      "dimensionFilters": [
       {
        "dimension": "Instance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-submit",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{Instance}} in {{resourceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "Instance",
        "filters": [
         "0--d2768151-449b-47a6-9e69-3f5134bb7c7b"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "northeurope",
        "resourceGroup": "inzynierka",
        "resourceName": "fa-worker",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "Server requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-submit",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-worker",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "TRACES",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 12 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{cloud/roleinstance}} in {{resourceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "traces/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-submit",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{cloud/roleinstance}} in {{resourceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "traces/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-worker",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "InstanceCount",
      "metricNamespace": "microsoft.web/sites",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "northeurope",
        "resourceGroup": "inzynierka",
        "resourceName": "fa-worker",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "InstanceCount",
      "metricNamespace": "microsoft.web/sites",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "fa-submit",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  }
 ]
}