{
 "title": "LOADBALANCER",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "USED SNAT PORTS by backend app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "USED SNAT PORTS by {{BackendIPAddress}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "BackendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "UsedSnatPorts",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/loadBalancers",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "kubernetes",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "SNAT CONNECTION BY backend app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "SNAT CONNECTION FOR {{BackendIPAddress}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "BackendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "SnatConnectionCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/loadBalancers",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "kubernetes",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "SYN CONNECTION COUNT BY IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "SYN Count {{FrontendIPAddress}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "FrontendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "SYNCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/loadBalancers",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "kubernetes",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "SNAT CONNECTION BY Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "SNAT Connection with status {{ConnectionState}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "ConnectionState",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "SnatConnectionCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/loadBalancers",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "kubernetes",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "Packet Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{Direction}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "Direction",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "PacketCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/loadBalancers",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "kubernetes",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  }
 ]
}