{
 "title": "PostgreSQL Database / Azure",
 "tags": [
  "azure",
  "db",
  "stats",
  "postgres"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "SERVER STATUS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "is_db_alive",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "CPU AND MEMORY INFO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "STORAGE INFO",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Storage Used",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_used",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Storage Free",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_free",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    { "expression": "$B +$C", "type": "math" }
   ]
  },
  {
   "title": "TOTAL TRANSATIONS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{servername}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "ServerName", "filters": [ "inz-postgres" ], "operator": "eq" }
      ],
      "metricName": "xact_total",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "TOTAL TRANSACTION by database",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{databasename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "DatabaseName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "xact_total",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "BACKUP INFO",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LogicalServerName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "backup_storage_used",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "IOPS INFO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "read_iops",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "write_iops",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "NETWORK ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
      "dimensionFilters": [],
      "metricName": "network_bytes_ingress",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "network_bytes_egress",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "DATABASE SIZE by name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "database size {{databasename}}",
      "allowedTimeGrainsMs": [
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "DatabaseName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "database_size_bytes",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "SESSIONS by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Session by state {{state}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [
       {
        "dimension": "State",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "sessions_by_state",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "CONNECTIONS INFO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "active_connections",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connections_failed",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/flexibleServers",
        "region": "northeurope",
        "resourceGroup": "Inzynierka",
        "resourceName": "inz-postgres",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  }
 ]
}