{
 "title": "VMSS",
 "tags": [
  "azure",
  "aks"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "RESOURCES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "VmAvailabilityMetric",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{resourceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{vmname}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "VMName",
        "filters": [
         "aks-inzynierka-13569243-vmss_85",
         "aks-inzynierka-13569243-vmss_86"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "Dics Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Microsoft.Compute/virtualmachineScaleSets",
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "DISK OPERATIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "RAM USAGE/TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{vmname}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Microsoft.Compute/virtualmachineScaleSets",
      "dimensionFilters": [
       {
        "dimension": "VMName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{resourceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "NETWORK ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  },
  {
   "title": "FLOWS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Inbound Flows",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Outbound Flows",
      "metricNamespace": "microsoft.compute/virtualmachinescalesets",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachineScaleSets",
        "region": "northeurope",
        "resourceGroup": "MC_Inzynierka_inzynierkaaks_northeurope",
        "resourceName": "aks-inzynierka-13569243-vmss",
        "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "dbb3dc1a-cb53-4add-a56f-c84e50cac7a1"
    }
   ]
  }
 ]
}